### PR TITLE
Added functions

### PR DESCRIPTION
**Pull request by ykornilov**
Hello!
Andrew, we added some functionality to work with HDL-equipment.
Please, merge it.

### CODE REVIEW

**Comment by caligo-mentis** [comment]
Hello Yuri!

Thank you for interest in this project!

First of all, you should not bump version in a PR, but should write tests and changelog for added functionality as well as follow existing codestyle in repository.

Before doing this I recommend you to wait some time because I have not published refactoring, which already contains many of these commands and will help you to add rest of them with ease.

**Comment by ykornilov** [comment]
Andrew, thanks for the answer! Is there an approximate time frame for the update?

**Comment by caligo-mentis** [comment]
I'll try to push these changes for preview this weekend.

**Comment by efa2000** [comment]
Very useful commands.
Please, merge it.

**Comment by caligo-mentis** [comment]
I've pushed [operation codes](https://github.com/caligo-mentis/smart-bus/tree/feature/operation-codes) branch. You can rebase this PR onto it only with new commands (or create a new one) or wait until I add all of these commands by myself. 

Also I can publish current state of this branch as new version to npm but main idea for next version is to provide simple way for extending available commands configuration on bus object programmatically.

**Comment by caligo-mentis** [comment]
All commands from this PR included in [v0.4.0](https://github.com/caligo-mentis/smart-bus/releases/tag/v0.4.0).

Better error handling will be implemented in the next release.

**Pull request closed without merging**
